"""
All protocol message type strings.
"""

MSG_AUTH = "AUTH"
MSG_AUTH_OK = "AUTH_OK"
MSG_AUTH_FAIL = "AUTH_FAIL"

MSG_COMMAND = "COMMAND"
MSG_RECEIVED_ACK = "RECEIVED_ACK"
MSG_STATUS = "STATUS"

MSG_HEARTBEAT = "HEARTBEAT"
MSG_HEARTBEAT_ACK = "HEARTBEAT_ACK"